version: '3.9'

services:
  console_app:
    build: .
    volumes:
      - .:/code
    command: sh -c "
      gradle clean
      &&
      gradle build
      && 
      ./gradlew test
      &&
      ./gradlew run
      " 
    environment:
      - ENVIRONMENT=developement
